
version: "3.4"
services:

  rundeck:
    image: rundeck/rundeck:3.4.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    environment:
      RUNDECK_GRAILS_URL: http://192.168.1.200
      RUNDECK_SERVER_FORWARDED: 'true'

  nginx:
    image: nginx:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


networks:
  - admin

networks:
  admin:
    external: true
